language: python
python: "3.6"
script:
  - pytest
  - pip3 install coverage
  - coverage run DBNsite/testing_DBNlogic/nets_test.py
after_sucess:
  - pip3 install codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=368b98cb3ee40b7b3c9ad38aab86d6ea29b0ad368ca90e7a8c3a66802dcc078b codeclimate-test-reporter
notifications:
  email: false
