language: python
python: "3.6"
script:
  - pytest --cov=DBNsite/DBNlogic
after_sucess:
  - pip install codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=368b98cb3ee40b7b3c9ad38aab86d6ea29b0ad368ca90e7a8c3a66802dcc078b codeclimate-test-reporter
notifications:
  email: false
